name: RestAPI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "**" ]

defaults:
  run:
    working-directory: ./rest-api

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle checkstyle
        run: ./gradlew -x test check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build task
        run: ./gradlew -x test -x check -x distTar -x distZip build

      - name: Execute Gradle test task
        run: ./gradlew -x check -x distTar -x distZip test
